### PR TITLE
Created vector graphic for the launcher foreground

### PR DESCRIPTION
**Pull request by sergeymasyura**
- Vector version of the ic_launcher_foreground was created (thanks to https://vectr.com/ for free vector graphics software).
- Old ic_launcher_foreground.png files were removed.
- New laucher icons were generated using Image Asset creator buil-in into Android Studio.
- Scaling of the foreground icon was slightly increased (110 percent comparing to original, feel free to edit).

### CODE REVIEW

**Comment by sergeymasyura** [comment]
@igorescodro If you do not accept contributions just close the pull request and update the readme for your project. Thanks.

**Comment by igorescodro** [comment]
Hello, @sergeymasyura. What do you think about using the same drawable resource as the exiting one which is used in the notification (ic_bookmark_check.xml)? This way if the launcher logo is changed to another asset, it will reflect in the notification icon as well. Thanks.

**Comment by sergeymasyura** [comment]
@igorescodro True, makes sense absolutely to utilize same icon for the launcher and notification, I did not notice that before. So, what was a point of placing png images in this case as launcher foregrounds? :) In this case this PR needs to be updated or new one created.

**Comment by igorescodro** [comment]
I didn't notice that until you submitted the change. I generated by Android Studio "New > Image Asset..." and hoped that it wouldn't convert to PNG. Or I submitted the PNG instead of Vector by mistake... 😬

**Pull request closed without merging**
